apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gathertown-server
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: gathertown-server
  template: 
    metadata:
      labels:
        app: gathertown-server
    spec:
      containers: 
      - name: server
        image: pawanhfl/gathertown-server:latest
        imagePullPolicy: Always
        
        volumeMounts:
        - name: secret
          mountPath: /usr/src/app/packages/db/.env
          subPath: .env
        ports:
        - containerPort: 3000 
      volumes:
      - name: secret
        secret:
          secretName: my-secret1  
          items:
            - key: .env
              path: .env
               


---

apiVersion: v1
kind: Service
metadata:
  name: gathertown-server
spec:
  selector:
    app: gathertown-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000