apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: status-cert
  namespace: default        
spec:
  secretName: status-tls     
  issuerRef:
    name: letsencrypt-prod  
    kind: ClusterIssuer
  commonName: status.itsarc.me
  dnsNames:
  - status.itsarc.me