apiVersion: apps/v1
kind: Deployment
metadata: 
  name: probo-engine
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: probo-engine
  template:
    metadata:
      labels:
        app: probo-engine
    spec:
      containers: 
      - name: probo-engine
        image: pawanhfl/probo-engine:5862fe6
        imagePullPolicy: Always
        env: 
        - name: REDIS_URL
          value: 'redis://redis-service:6379'
