apiVersion: apps/v1
kind: Deployment
metadata: 
  name: probo-server
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: probo-server
  template: 
    metadata:
      labels:
        app: probo-server
    spec:
      containers: 
      - name: probo-server
        image: pawanhfl/probo_server:5862fe6
        imagePullPolicy: Always
        env: 
        - name: REDIS_URL
          value: 'redis://redis-service:6379'
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: probo-server
spec:
  selector:
    app: probo-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000