apiVersion: apps/v1
kind: Deployment
metadata:
  name: probo-ws
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: probo-ws
  template:
    metadata:
      labels:
        app: probo-ws
    spec: 
      containers: 
      - name: probo-ws
        image: pawanhfl/probo_ws:5862fe6
        imagePullPolicy: Always
        env:
        - name: REDIS_URL
          value: 'redis://redis-service.default:6379'
      
---

apiVersion: v1
kind: Service
metadata:
  name: probo-ws
spec:
  selector:
    app: probo-ws
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080